### ISSUE TITLE
Add esModuleInterop typescript option

### ISSUE THREAD

**Issue by syeutyu** [privatenumber/tasuku#6]
## Is your feature request related to a problem?
No

## Describe the solution you'd like
When I install and use the tasuku library with typscript project
I have written code following this library document.

But I faced `is not a function error` and I founded issue point.
```
import task from "tasuku"

// it same below code without esModuleExport
const task = require("tasuku").default;
```
So I printed it and that is undefined.

## Describe alternatives you've considered
Of course, it is not an important issue.

But How about the option was left in the readme.md?
I think it would be greater before then.

And I'm using this library very useful! thanks 😄

**Comment by privatenumber** [comment]
Thanks for providing the reproduction details.

I looked into it but I think this is more of a user-land, general, TypeScript configuration issue than a tasuku documentation one (because it can happen with any ESM file importing a CJS module).

It seems [the docs](https://www.typescriptlang.org/tsconfig#esModuleInterop) recommend using `esModuleInterop` anytime you're using ESM so you should have that on regardless of whether you're using tasuku.

There also appears to be other solutions too including: `import task = require('tasuku')`.

**Comment by privatenumber** [comment]
Actually, I found another improvement by exporting the dts via `export = task`. This gives a warning:

```
Module '"tasuku@1.0.2/node_modules/tasuku/dist/index"' can only be default-imported using the 'esModuleInterop' flag ts(1259)
```
