### ISSUE TITLE
Redraw glitch when list of task is long

### ISSUE THREAD

**Issue by bobylito** [privatenumber/tasuku#7]
## Bug description

This is a visual bug. When the list of items is bigger than the screen height, the list starts glitching.

![2021-11-30 09 55 01](https://user-images.githubusercontent.com/393765/144016043-12017400-be6c-4e9d-a2cf-0edbc47103d5.gif)

## Reproduction

```js
const task = require("tasuku");

(async function test() {
  let iteration = 0;
  while (true) {
    await task(
      `Run ${iteration} -- with long text it is more visible`,
      () => new Promise((resolve) => setTimeout(() => resolve(), 100))
    );
    iteration++;
  }
})();

```

## Environment

- tasuku version: 1.0.2
- Operating System: MacOS 12.0.1 with ITerm2 3.4.12
- Node version: 14.18.0 and 15.14.0 (inside docker)

**Comment by privatenumber** [comment]
This is a known limitation in [Ink](https://github.com/vadimdemedes/ink), the renderer tasuku is using. It might be by design since only re-rendering what's in the viewport could break native scrolling.

To work around this, I recommend limiting your list so that it's not longer than your viewport. This leads to better UI/UX anyway, so it's an overall plus.

If you want to If your processing flow is in series, run `clear()` on each completed task so it's removed. If in async, use a concurrency manager like [p-map](https://github.com/sindresorhus/p-map) so it only does _n_ number of tasks at once. I have also consolidated a large list of tasks to one and updated the count of completed ones via `setStatus` or `setOutput` instead.

I will leave this open until I add a "Best practices" section in the README recommending this.

**Comment by bobylito** [comment]
Thanks for following up on this issue. Your recommendations are great.
